name: Build

on:
  pull_request:
    branches:
      - master
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy to gh-pages
      run: |
        npm install
        npm run stitchjson
        npm run build
